version: '3.8'

services:
  pihole:
    # https://hub.docker.com/r/pihole/pihole/tags
    image: pihole/pihole:2023.11.0
    depends_on:
      - cloudflared
    container_name: pihole
    environment:
      - TZ=Europe/London
      - WEBPASSWORD={{PIHOLE_WEBPASSWORD}}
      - PIHOLE_DNS_=cloudflared#5054
      - DNSSEC=true
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmaskq.d/:/etc/dnsmasq.d/
    labels:
      - traefik.enable=true
      - traefik.http.services.pihole.loadbalancer.server.port=80
    restart: unless-stopped
    networks:
      - default
      - proxy

  cloudflared:
    # https://hub.docker.com/r/visibilityspots/cloudflared/tags
    image: visibilityspots/cloudflared:v2023.10.0
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - default

networks:
  proxy:
    external: true
