version: '3.8'

services:
  traefik:
    # https://hub.docker.com/_/traefik/tags
    image: traefik:v2.10.7
    container_name: traefik
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
