---
- hosts: pi
  name: Set up Raspberry Pi

  pre_tasks:
    - name: Load config
      tags:
        - pihole
        - plex
      ansible.builtin.include_vars: ./config.yml

    - name: Update apt cache
      become: true
      tags:
        - upgrade
        - essential
      ansible.builtin.apt:
        update_cache: true

  roles:
    - role: upgrade
      tags: upgrade

    - role: essential
      tags: essential

    - role: docker
      tags: docker

    - role: proxy
      tags: proxy

    - role: pihole
      tags: pihole

    - role: plex
      tags: plex

    - role: nextcloud
      tags: nextcloud
