version: "3.8"

services:
  pihole:
    image: pihole/pihole:latest
    depends_on:
      - cloudflared
    container_name: pihole
    environment:
      - TZ=Europe/London
      - PIHOLE_DNS_=cloudflared#5054
      - DNSSEC=true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmaskq.d/:/etc/dnsmasq.d/
    labels:
      - traefik.enable=true
      - traefik.http.services.pihole.loadbalancer.server.port=80
    restart: unless-stopped
    networks:
      - default
      - proxy

  cloudflared:
    image: visibilityspots/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - default

networks:
  proxy:
    external: true
