---
- name: Copy proxy files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: ~/services/proxy/
    mode: '0644'
  loop:
    - docker-compose.yml
    - traefik.yml

- name: Create external Docker network
  community.docker.docker_network:
    name: proxy

- name: Start proxy services
  community.docker.docker_compose:
    project_src: ~/services/proxy/
    restarted: true
