---
- name: Set up dns
  tags: dns
  block:
    - name: Set dns servers
      become: true
      ansible.builtin.lineinfile:
        path: /etc/dhcpcd.conf
        line: static domain_name_servers=1.1.1.1 1.0.0.1
        regexp: '^static domain_name_servers='

    - name: Copy dns files
      ansible.builtin.copy:
        src: ./dns/
        dest: ~/services/dns/
        mode: "0644"

    - name: Copy docker-compose.yml
      ansible.builtin.template:
        src: ./dns/docker-compose.yml
        dest: ~/services/dns/docker-compose.yml
        mode: "0644"

    - name: Start dns services
      community.docker.docker_compose:
        project_src: ~/services/dns/
        restarted: true
