---
- name: Upgrade dist
  become: true
  ansible.builtin.apt:
    upgrade: dist
  register: upgrade_result

- name: Reboot
  become: true
  ansible.builtin.reboot:
  when: upgrade_result is changed

- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: "yes"

- name: Remove unused packages
  become: true
  ansible.builtin.apt:
    autoremove: true
