version: "3.8"

services:
  plex:
    build:
      context: ./pms-docker
      dockerfile: Dockerfile.arm64
    container_name: plex
    environment:
      - TZ=Europe/London
      - PLEX_CLAIM={{PLEX_CLAIM}}
      - ADVERTISE_IP=http://192.168.8.248:32400/
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ./database:/config
      - /mnt/hdd/media:/data
    labels:
      - traefik.enable=true
      - traefik.http.services.plex.loadbalancer.server.port=32400
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
