version: '3.8'

services:
  nextcloud:
    # https://hub.docker.com/r/linuxserver/nextcloud/tags
    image: linuxserver/nextcloud:28.0.1
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/hdd/nextcloud/config:/config
      - /mnt/hdd/nextcloud/data:/data
    labels:
      - traefik.enable=true
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
