version: "3.8"

services:
  traefik:
    image: traefik:v2.9.6
    container_name: traefik
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

networks:
  proxy:
    external: true
