---
- name: Clone pms-docker repo
  ansible.builtin.git:
    repo: https://github.com/plexinc/pms-docker/
    dest: ~/services/plex/pms-docker/

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml
    dest: ~/services/plex/docker-compose.yml
    mode: '0644'

- name: Start plex
  community.docker.docker_compose:
    project_src: ~/services/plex/
    restarted: true
