---
- name: Set dns servers
  become: true
  ansible.builtin.command: nmcli d modify eth0 ipv4.dns "1.1.1.1,1.0.0.1"

- name: Copy pihole configuration files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: ~/services/dns/
    mode: '0644'
  loop:
    - etc-dnsmaskq.d
    - etc-pihole

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: ./dns/docker-compose.yml
    dest: ~/services/dns/docker-compose.yml
    mode: '0644'

- name: Start dns services
  community.docker.docker_compose:
    project_src: ~/services/dns/
    restarted: true
